// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "nøgle0":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image2":
            case "nøglee":return img`
. . . . . . . . . . . . . . . . 
. . . 5 5 5 5 5 5 . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 5 . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. 5 5 5 5 . . . . . . . . . . . 
5 5 4 4 5 5 . . . . . . . . . . 
5 5 4 . 5 5 . . . . . . . . . . 
5 5 5 5 5 4 . . . . . . . . . . 
. 5 5 5 4 . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "LukketKiste":return img`
. . b b b b b b b b b b b b . . 
. b e 4 4 4 4 4 4 4 4 4 4 e b . 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
. b b . . . . . . . . . . b b . 
`;
            case "image4":
            case "pad":return img`
a a a c c a a a a a a c c a a a 
3 3 3 3 c 3 3 3 3 3 3 3 c 3 3 3 
3 3 3 a c 3 3 3 3 3 3 3 c 3 3 3 
a a a a c a a a a a a a c c a a 
c c c c c d d d d d d c c c c c 
c a 3 3 c d c 4 4 d d c 3 3 3 a 
c c a a c d c 4 4 d d c a a a a 
c c c c c b b c d b b c c c c c 
a a a c c b b c d b b c c a a a 
a a a c c b b c c b b c c a a a 
c c c c c b b c c b b c c c c c 
c a a a c b b c c b b c a a a c 
c c c c c b b b b b b c c c c c 
a a c c a c c c c c c c a a a a 
c c c c c c c c c c c c c c c c 
c c c c c c c c c c c c c c c c 
`;
            case "ZZ2$P1GNIQ{!OrO#11I*":
            case "Haunted Village":return img`
ffffffffffcfffffffffffcccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffccc
fffffcccfccfffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffccc
fffffffffcffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffcc
ffffffccffffffffffffffcccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffccccccccccccccccccccccccccccccccfffffffc
ffffffffffffffffffffffccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccfffffffffffcccccbcccccccccccccccccccccfffffffc
fffffffcfffffffffffffffcccccccccccccfcfcccccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccbccbcccccfffffffffffffffffcccccccccccccccccccccffffffff
ffffffccfffffffffffffffccccccccccccccfcccccccfccccccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffcccccccccccccffffffff
ffffffcffffffffffffffffccfccfccccccfccccccccccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccfcffcfffccfffffffffffffffffffffcccccfffffffc
fffffcfffffffffffffffffccfcfccccccccffccccccccccccccccccccccccccccccccccfcccffcccccccccccccccccccccccccccccccccccccffffcffccccccccccfffffffffffffffffffffffffff
fffffcfffffffffffffffffccccccccccffcfcccccccccccccccccccccccccccccccccccfccccfccccccccccccccccccccccccccccccccccccccfffffcccccccccccccccccfffffffffffffffffffff
fffffffffffffffffffffffcccfccccccfccfcccccccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccffffcccccccccccccccccccccccffffffffffffffff
fffffffffffffffffffffffccccfcccccfccfcccccccccccccccccccccccccccccccccccffcccccccccccccccccccccccccccccccccccccccccccfffccccccccccccccccccccccccccccfffffffffff
fffffffffffffffffffffffccccfcfcccccfccccccccccccfccccccccccccccccccccccccfccccccccccffcccccccccccccffccccccccccccccccffcccccccccccccccccccccccccccccccfffffffff
fffffffffffffffffffffffcfccfcccffccccccccfccccccffcccccccccccfffcccccccccccccccccccccfcccccccccccccccccffffffcccccccccccccccccccccccccccccccccccccccccfcfffffff
ffffffcccfffffffcffffffcfccccccffccfccccccccccccffccccccccccccffcccccccccccccccccccccccccccccccccccccccccccccccccfffffffccccccccccccccccccccccccccccccfffccffff
ffffccccccffffccfffffffcccfccccccfcfcccfccccccccfffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffcccccccccccccccccccccccffffccfff
fffccccccccfffccfffffffccfcccccfcccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccfcccccccccccffffcccccccccccccccfffffffff
fffccccccccccfccfffffffcfcccccccfccfcfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccfcccccccccccccccccfffffffff
fffccccccccccfccfffffffcccccccfccccfcccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffff
cffccccccccccfccfffffffccccccfccccfccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccfcccccccccccccccccffffffffff
ccccccccccccccccfffffffccccccccfccfccccccccccccccccccccccccccffbbbcccccccccccccccccccccccccccccccccccccccffccccccccccccccccccccccccccccccccccccccccccffffffffff
fccccccccccccccfffffffffccccccccccfcfccccccccccccccccccfcccbccfbbbbbbbbbbcccccccccccccccccccccccccccccfcfcfffccccccccccccccccccccccccccccccccccccccccffffffffff
ffccccccccccccccffffffffccccccfccffccccccccccccccccccccfcccccbccbbcccbbccccccccccccccccccccccccccccccfccccccfffccccccccccccccfccccfccccccccccccccccccffffffffff
ffccccccccccccccffffffffcfccccccffccccccccccccfccccccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccffffcccccccccccccccfffccccccccccccccccccffffffffff
fffcccccbcccccccfffffffffccccfcffccccccccccffccccccccccffccccccccccccccccccccccccccccccccccccccccccccccccccccccfffcfffcfcccccfffcffccccccccccccccccccffffffffff
ffffcccccccccccccfffffffccccccffccccccccccffccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffcccffffcccfccccccccccccccccccffffffffff
fffffccccccccccccfffffffbcccfffcccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffccccccccccccccccccccccccffffffffff
ffffffcccccccccccfffffffbccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffccccccccccccccccccccccccffffffffff
ffffffccccccccccccffffffcffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffcccccccccccccccccccccccccfffffffffff
fffffffcccccccccccffffffcfcccccfcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffccccccccccccccccccccccccccfffffffffff
ffffffffccccccccccffffffcccccccccccccccccccccccccccccccccccccccccccccffcccccccccccccccccccccccccccccccccccccccccccfffffffcccccccccccccccccccccccccccfffffffffff
fffffffffcccccccccffffffcccccffccccccccfccccccccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccfffffffcccccccccccccccccccccccccccfffffffffff
fffffffffcccccccccfffffffbccbfccccfcccccbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcfffffcccccccccccccccccccccccccccfffffffffff
ffffffffffccccccccfffffffccbbfccccbbbcccbbbbbbbbbcccccbbbcbbcbbbbcccfcccccccccccccccccccccccccccccbbbbbccbbbcccccccfcffffcccccccccccccccccccccccccccfffffffffff
fffffffffffccccccccffffffbcbcfcbbbbbbbfbbcccbbbbccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccffffffcccccccccccccccccccccccccbcfffffffffff
fffffcffffffcccccccffffffcbccbbbbbbbbbcbbbbbcbccbbbbbbbbbbbbbbbbbbcccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbccccfcffffcccccccccccccccccccccccccccfffffffffff
fffffffffffffccccccffffffcffcbbbbbbcccccccccbfbbccccbbbbbbbbbbbbbbbccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccfffffccccccccccccccccccccccccbbffffffffffff
fffffffffffffccccccffffffcfcbbbcccccccccccccccccbcbcbbbbbbbbbbbbbbbbbcccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccffffffcccccccccccccccccccbbbbbbcffffffffffff
fffffffcffffffcccccffffffcccbbccccccccccccfccccbbbbbbbbbbbbbbbbbbbbbbcbcccbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccffffffccccccccccccccccccbbbbbbbfffffffffffff
fffffffffffffffccccffffffccbbccccccccfcfcfcccbbbbbbbbbbbbbbbbbbbbbbbccbcccbcccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbcfcffffccccccccccccccccbcbbcbbbfcffffffffffff
fffffcffffffffffccfffffffcbbbcccccccccccccbbbcbbbbbbbbbbbbbbbbbbbbbccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccffffffccccccccccccccccccbccccffffffffffffff
fffffffffffffffffccffffffccbbcccccfcccccccbbbbbbbbbbbbbbbbbbbbbbbbbcbccccccccccccccccccbbbbbbbbbbbbccbbbbbbbbbbbbcffffffffccccccccccccccccccccccffcffffffffffff
ffffffffffffffffffcfffffffcbbcccccccccbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccbbbbbbbbbbcccbbbbbbbbbbbbbcffffffffccccccccccccccccccccbfffcfffffffffffc
ffffcffffffffffffffcffffffcbcbcccccccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccbbbbbbbbbcccccbbbbbbbbbbbbbffffffffccccccccccccccccccccccfccfffffffffffc
ffffcfffffffcfffffffcfffffcbbcccccbcccbccbbbbbbbbcbccbbbbbbbbbbbbbbbbbcccccccccccccccbbbbbbbbbbbcccccbbbbbbbbbbbbbffffffffccccccccccccccccccccffcfcffffffffffff
ffffffffffffcffffffffffffffbbbcccccbbcccccccccccbbbbbbbbbbbbbbbbbbbbbbbbccccccccbbccbbbbbbbbbbbbbbcccbbbbbbbbbbbbbcfffffffcccccccccccccccccccffcffcffffffffffff
ffffffffffffcffffffffffffffcccccccbbbbcbbbbbbbbbccccbbbbbbbbbbbcbbbbbbbccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffffffcccccbbbbbcccccccccccffcffffffffffffc
ffffffffffffcffffffffffffffccccccccbbcbbbbbbbbbcfbbbbbbbbbbbbbbccbbbbccccccccccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcffffffcbbbbbbbbbbbbbbbcccccfcfcffffffffffffc
fffffffffffccfcccdddbccffffccbcbbccccbbbbbbbbbccccccbcbbbbbcbcccbccbcccccccccccccbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcffffffcbbbbbbbbbbbbbbbbbccccfccfffffffffffff
ffffffffffcfffcccbdddccbbcccbcbbbbbbcbbbbbcccccbccccccccbcccbcccbbbccccccccccbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccffffccbbbbbbbbbbbbbbbbccfccffcfffffffffffff
fffffffffffcffccbbddbccfcccbccbbbbcccccccccccbbbbcccccccbcbcbcccccbcbccccccccbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccffffbbbbbbbbbbbbbbbbbbffccfffcfffffffffffff
fffcffffffffffccbbbcfccffbccfcccccbbbbbbbbbbbbbbbbcccccbbcbbbcbccccbccccccbccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccfffbbbbbbbbbbbbbbbbbffffffffcfffffffffffff
fffcccffffffffccbccccdbcbcddddbcbcccbbbbbbbbbbbbbbbbbbbbbccbbccbccbbbcbcccbcbbcbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcccfffbbbbbbbbbbbbbbbbccfffffffcfffffffcfffff
fffcccfffffffccdcccbddcbddbdddbcbbbcccbbbbbbbbbbbbbbbbbbbccbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbbcbffffbbbbbbbbbbfbbcffcfffffffffffffffccfcfff
fffcccffffcffccbfcbbbccdddbdddbcbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbcbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbbbffffbbbbbbbbbbffbfcffcfffffffffffffccccccff
fffcccfcffcffcbccccbccbbbdcdddccbddbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffbbbbbbbbbcfffcfffffffffffffffffccccccff
fffcccffffcffffcbcccccfcbccdddcccddbdddccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffbbbbbbbbbffffccffffffffffffffcfccccccff
fffcccffffccffcdcccccccccbbccbcccddddbddbbcccdbbbbbcbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffbbbbbbbbcfffcffffffffffffffcfccccccccff
ffccccfffffcffcdccccbbddbcbcdcccccdddddddbbbbccbccbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfffbbbbbbbbccffcffcfcccfffcfffcccccccccfff
ffcccccfffccfc1dfcccddddddbcbccccc1dddddddddddbdbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcffcbbbbbbdccfffcccccccdfffcffcccccccccfccf
ffcccccffffcfddfccccddddddddccccccbddddddddbbbbdbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbcccfccccccfdfcfcffccccccccffccf
ffccccffffccfcfccccbddddddbbccccccbfcccbdccbcdbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcbbbbbdcccfcfcccccccdcccccfccccccccccccf
ffffccfffffcfffccccbdddddddbccccccb1dddddddddddbbbbbbbbbbbbbbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcbbbbbbbcccffccccccfbcccccfcccccfccccccf
fffffcfffffcfcddcfcbbbbdddccccccccfc1dddddbbdbbbbbbbbbbbbbbbbbbbccccbbbbbbbddddddddddddddddddbddbbbbbbbbbbbbbbbbbbbbbfffbbbbbcbccccccccccccccccfcccccccfccccccc
ffcfffffffccfbddcfcbbbbddddbcccccfccdddddddddddbbbbddddddbbbbbbbccccbbbbbbbddddddddd11d1dddd1ddddddddddddddbbbbbbbbbcfffbbbbbbccccccccccccccccffcccccccccccfccf
ffccffffffccffffffcbbbbdddddcccbcbdddddddddddddddddddddddddddddbccccbbbbddddddddddd1ddddddddddddddddddddd11ddddbbbbbcfffbbbbcfcfcfcfcccccccccfccccccccccccccccc
ffccffffffccfd1bcfccbbbdddddcccbccddd1dddddddddddddbbdddddddddddccccbbbdddddddddd1ddddddddddddddddddddddddddd1ddddddffffdddbccccccccccccccccccfcfccccccccccfccc
cfccffcfffccfd1ccfccbdddddddcccdcbbddd111dddddddddbbbdddddddddddccccbbddddddddd1111dd1ddddddddddddddddddddddddddddddffddddbccccccccccccccccccccfcccccccccccfccc
cfccffcccffffccccfccccddd1ddbbfdcb1dddd11dddddddddddddddddddddddcccccccdddd111111d11dd1dddddddddddddddddddbbbbbbddddcfdddbccbccccccccccffccccfcfcccccccccccfccc
cfccffcccccffccccfcccccccccccccccccccbbbb1dddbbbddddddddddddddcccccccccbddd111111111ddddddddddddddbbdbdddbbbbbbbdddddddddcccbccccccccccffccccfcfcccfcccccccfcfc
cfccfcfcccccfccccfcccccccccccccccccccccccd11dcccdddddddddddddbccccccccccd11111111dddddddddddddddbbbbbbbbbbbbbbbbddddddddddcccccccccccccffccccfccffcccffccccfccc
cfccfffbccccfcccccccccccccccccccccccccccf1dddccbdddddddddddddbccccccccccd11111dddddddddddddddddbbbbbdbbbbbbbbdbbdddddddb11bcbccccccccccfcccccfcccccffccffccfccc
cfccccfbccccfcccffcccccbcccccccccfcccccfccbbbccbcbccbddddddddbccccccccccb11111dd111dddddddddddddbbbbbbbbbbbbbdbdddddbbbbbbcbbcccccccccccfccccfccccfccccffcccccc
cfcfccfcccccfcccffcccccfccccccccccccfcccccccccccccccbddddddddbccccccccccbd1111dd11dddd1dddddddddbbbbdbbbbbbbbdbdbdbbcbbbbbcbbccccccccfccfccccffccffccccffcccccf
cccfccfcccccccccfcfffccfcccccccccccccccccfccccccccccbddddd1ddcccccccccccbd11ddd11ddddd1dddddddddbbdbbbbbbbbdddddbbbbcbbbbbcbccfffccccfcccccccffccffccccffcccccf
cfcfcbfffcccfcccffcffccffccccccccccccfffccccccccccccbd1ddd11bcccccccccccbb1ddd111dddddddddddddddddddbbbbbddddddbbbbbccbbbbcccfcffccccfcccccccffccffccccfffccccf
cfcfccccffccfccffffffccfffcccccccccccfffccccccccccccbdd1dd11ccccccccccccccccdd111ddddddddddddddddddbbbbbbbddddbbbbbbfcbbbbcccffffccccffcccccccfccffcffccccccccf
cfcfccccffccfccfffffffcccffcccccccccfcccccfcccccccccbdddd111ccccccccccccccccbbd11111dddddddddddddddbbbbbbbbddbbbbbbbccbbdbcccffffcccccccccccccfccffcfcccffccfff
ffcffccfffccfccffffffffffffcccccccccfcfccffcccccccccbdddd111ccccccccccccccccbbb111111dddddddddddddddbbbbdddddbbbcbccfccccbbcccfffcffccccccccccffcffccfffffcfffc
fccfffcfffccfccfffffffffffffccccccccfccffffcccccccccbdddddd1ccccccccccccccccbbb1d11111dddddddddddbdbbbbbdddbddcccccccbccfcfcfcffffffccccccffccffffcffffcffffffc
fcfccfffffccfccffffffffffffffcffcccccfcffcffccccccccbdddddccccccccccccccccccccb1d1111d1dddddddddddbbbbbbddbbdbccccccccccccccfccfffffcccccffccffffccfffcffffffcc
fcfffffffffcfccfffffffffffffffcffcccfffcfcffbcccccccbdddddcccccccccccccccccccccdbddd111ddd1ddddddbdbbbbbdbbbddbcccccccfcccccfcffffffccccccccffccffcfffffffcffcc
ffffffffccfffcfffcfffffccfffffffcfffffffffffccccccccbdddddccccccccccccccccccccccbbbc11ddddddddddddddbbbbdddbddcccccccfcccccccffffffccccccccccccffffffffffffffff
fcfffffffffcfcfffcffffcccfcfffffcffffffcfffffcccccccbdddddccccccccccccccccccccccccccd1ddddbbdddddddbbcccddddddcccccccfccccccccffffccccfccfcccfcfcfffffcffcfffff
fcfffffffffffffffcfffffccccfffffcfcffffffffffcccccccbddddccccccccccccccccccccccccccccdbddcbdddddddddbcccbbddddfccccccfccccccccfffffccccccfccfffffffcfcccfffffff
fffffcfcffffffcffcfffffcccffcffffffffffffffffcccccccbdbbccccccccccccccccccccccccbcccbbddbccdbdddddbbbcccbfddbbfccccccfccccccccccfffcffcccccccfcfffccccffffffccc
ffffffffffccffcffccffffccccfcffffffccffffffffcfffcccbdbbccccccccccccccccccccccbccccbbdbdcccbbd1dddcccccccfccccfbcccccfcccccccccfcffffffffffffffcffcffffffffcfcc
cffffcfcffcfffcffffffffcccfffffffffffffffffffccffcccbbbbbccccccccccccccccccccbbbcccbcbbdcccbbd1bdbcccccfccccccfbcccccffccccccccccfffffffffffffcffffcfffffffcccc
cfffcfcfffffffcffffffffffcfffffffffffffffffffccfccccddbbbcccccccccccccccccccbcbcbccccccbccccbddbdbcccccccccfccfccccfcfccccccccccffffffffffffffffffffcffffccccfc
ccccccffffffffffffffffffffffffffffffffffffffffccffcfbbdcbbbccccccccccccccccccccccccccccbcccccbdbbbccccccccccccfcbccccfcccccccccccffffffffffffcffffffffffcfccccc
fffffffcffffffffffffffffffffffffffffffffffffffccfccffbbccbbbccccccccccccccccbcccccccccccccccccbcbcccccccccccfcfccccccfccfcccccfffffffffffffffcfffffffffffcccffc
ffffffffffffffffffffffffffffffcfffffffffffffffcbffcffcccccccccccccccccccccccbcccccccccccccccccccccccfccfccffccccbcfcfffcfcfffffffffffffffffffcfffffffffcfffffff
ffffffffffffffffffffffffffffffccffffffcffffcffccffccbbcccccccccbbcccffccccbbccccccccccbccccccccbbcccccccfffffcfcbcccfcfcffcfffffffffffcffffffcfffffffffffffffff
ffffffffffffcfffcffcfffffffcfcfcffffcfcffffcffcccfccbbcccccccccbbcccffccccccbccbcccbccbbbcbccbbbcccccccffffffcfcccfffffcffcfffffffffffcffffffcfffffffffffffffff
fffffffffffffffffffffffffffffffffcfcffcffcfcffcbffcbbbbccbccccccccccffccccccccccbbcbccbbccccbcbbccccccffffcffffccffffffcfccfffffffffffcffffffcfffcfcfffffffffff
fffffffcffffffffffffffffffffffffcfffffcffffcfffbffcbbbbcccccccccccccccccccccbcccbbbbcccbcccccbcbccccccffffcfccfffffffffcfcccffffffffffcfffccfcfffffcfffffffffff
fffffffcfffffffffffffffffffffffffffffffffffcffbccfcbccbcbcccccccccccccccccccccccccbccccbcbccccbcccccccffffcfffffffffcffcfccccfffffffffcfccccfcfccccfcffffffffff
fffffffffffffffffffffffffffffffffffffffcffffffcbcfcbcccbbbbccccccfccccccccccccccccccccccbbbccbbcccccccffffcfffffffcfccfcccccffffffffffcffcccfccccccfcffffffcfff
ffffffffffffffffffffffffffffffffffffffcfffffffcbcfccccccbbccccccccccccccccccccccccccccccbcccccccccccfcffffcfcfffffcffffcccccffffffffffcffffccccccccfcffffffffff
fffffffccffffffffffffffffcffcffffffffcfffffffffcccccccccbbbccccccccccccccccccccccccccccccccccccccccccfffcfcfffffffcffffcccccffffffffffcffffcfccccccffcfffffcfff
ffffffcccffcfffffffcfffffccfcffffffffffccccfffcffffcccccccccccccccccccfcccccccccccccccfcccccccccccccccfffccccffffccfffcccccccffffffffffffffffffffffffffffffffff
ffffffccfffffffffffccfffffcccccccfffffcccccffffffffcccccccccccccccccccccccccccccccccccccccccccccccccffffccccccfffccfcfcccccffffffffffffffffffffffffffffffffffff
ffffffffffcfffffffcfffffffccfccccffffccccccfffffffffccffcccccccccccccccccffccccccffcfffccccccccccccccccfcccccccffccfcffcffffffffffffffffffffffffffffcffffffffff
fffffffffffffffccfffffffffcfcccccffffcccccffffffffffcfffccccccccbcccccccccccccccccccffcfccccccccccccccccccccccccfccfffffffffffffffffffffffffffffffffcffffffffff
fffffffcfcfccfffcccfffffffccfcfccffffccccffffffcfffccfffcfcccccccccccccccccccccccfccffcfccccccccccccccfffccffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffccfffffffcffccffffffccccfcfffffccccccfffffffffccffcccccccccccccccccccfcfcfffcffffffcccccccccfffffffffffccffffffffffffffffffffffffffffffffffffffffffffffff
ffffffccfffffffffffcffffffccfcfcfffffccccccccffffffcffffcccccccccccccccccccccccccccfffffffcccccccccfccfffffcccccfffffffffffffffffffffffffffffffffffffffffffffff
fffffffffcffcffcffcfffffffccfcfffffffcccccccfffccfcfffccccccccccccccccccccccccccccccffcfccccccccccccccccfffccccccfffffffffffcffffffffffffffcfffffffcccfffffffff
ffffffccfcfffffcfcccffffffcccccfffffccccccccccffffffffcccccccccccccccccccccccccccccccfffccccccccccccccccffccccccccffcfffffcffffffffffffffffffffffffccffffffffff
ffffffccffffcffccfccffffffccfccccffffcccccccfffbcccbcccccccccccccccccccccccccccccccccccfccccccccccccccccffcccccccccfccffffcfcffffffffffffffcfffffffccffffffcfff
ffffffccffffcffcccccffcfffccccfcccfcfccccccccffbcccbccccccccccccccccccccccccccccccccccffccccccccccccccccfccccccfcfffcfffffcfcccffffffffffffffffffffccccffcfccff
ffffffcccffffffcfcccffffffcccfcccfffffccfcfcccfbcccccccccccccccccbcccccccccccccccccccccfcccccccccccccccccccccccccfffffcffffcccccccccffffffffffffffffcfcffcfccff
ffffffccccffcffffccfffffffcccfccfccccfcffcfccfffcccccfccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccffffffcfccffcffcfffcccfffffffffccccfccfccff
ffffffccfcfffffffcccffffffcccccfccffffccfccccffbcccbcfcccccccccccccccccccccccccccccccccccccccccccfccccfffccccccccfccfcfffffffcccfffffffcccfffffffffccccfcccccff
ffffffccffcffffffcccffffccccccccfcffffccfcccfffccccccfccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccfcfcffcccfffffffffffffccffffffffffccccfcccccff
ffffffccffffcffffffffcccccbcfffffcffffccfcccccfcccccffcbbccccccbbbcccccccbbccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffccfffffffffccccffccccff
ffffffccfcffffcffccfffffffffffcffffffffcfcfcfffcccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccffccfccfffffffffffffffcccffffffffffcccfcccccff
ffffffcfffffffffffffffccccccccfffffffffffcfffcfffffcfcffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffcccffffffffccffcfcccccff
ffffffcfffffccccffffcffccfffffcfffffffffccffffcffffffccffccccccbcfccccbbbcccccccccccccccccccccccccccccccfccccccccccccffcffffffffffffffffffffffffcfccffcfcccccff
fffffffffffffcfcffffffcffffffffffffffffffcfffffcfffcfcccfcccccbcfccccccccccccccccccccccccccccccccccccccccccccccccfccfffffffffffffffffcfcfffccccfffcfffcffccccff
ffffffffffffcccccfffffccfccccccffffffffcfffffffffffccfcfffccccccfbcbccccbbbbdbccccccccccccccbbccccccccccccccccfcccccccccfffffcccccfffcccfcfccccffcffffcffcffcff
ffffffffffffffcccffffcfcccccccccccccffffffffffffffffffffffccbccfcbccccccccccccccccbbcccccbbbbbccccccccccccccccfcccffffcfcffffcfffffccfccffcccffffcffcccfffffcff
ffffffffffffcfccccfcccfccccfccccccccccffffffffffffffffffffcccccfccccccccccbccccccccbbbbbbccccccccbcccccccccccccffccfcfffccffcffcfccccfcccfcffcccfccffffffffccff
fffffcffffffffffffffffffffffcfffffffffffcccccfccccccccccccccccbfcccccccbcbbbbccccccccccbbbbcbcbbbcccccccccccccccccccfcfcffffffffffcfcccccffffffcfccfffffffffcff
fffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffccccfcccccccccccccccccbbbbcbbbbcccbbcccccccccccccccccfcccccccccfcfccfcccccccfccffcfcfcfffffffffffcff
fffffffffffffffffffffffffffcfccccccccfffffffffffffffffffffffcccfccccccccccccccccccbbcbcbbcccbbbbcccccbbccccccccccccccccccccccccccffcccfffffffffffcccffffcffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccfccccccccccccccccbbbbbcbbbccccbcdbcbcbbbbbbbbbcccccccccfffffffffffffffffffffffffffcffffffcffcccf
ffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfccccbdbbdbcccbdbbbcccccccbbcccbcccccccccbccccccccccccfffcfffffffffffccfffffffffffffcccf
ffccffffffffffffffffffffcffffffffffffffffffffffffffffffffffcccffcccfcccccbccbbccbcbcccbccbccccbcccbccccfccccccccccccccccccccccfccccfccffffccfffffffffffcccfcccf
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfcccccbbccccccccbcbcbcbbccccccbccccccccccccccccccccccccccfffffccccfccfffffffffffffffffffffffff
fffffcccccfffffffffffffffffffffffffffffffffffffffffcfffffffccfcccccccccccccbbccbccccbbbbbbcccbddbbdbbbbccbccccccccccccfcfffccffffffffcccfffcfffffffffffffffffff
cccccccffffffffffffffffffffcffffffffffffffffffffcfffccccccccfffccccfcccccccccbdbbbcccbcccccccccbccccccbcbcccccbcccccccccccccfccccfccfcccfffffffffcfffffffffffff
cccfffffffffffffffffffffffcccfffffffffccffffffcccccccfffffccccccccccccccccccbdbbccbccccbbbcccccfcccccccbcbbbcccccccccccccccccccccffffcccfccffffffffffffccffffff
ffffffffcfcccfffffffffffffffffffffffcccffcfccfffffcccccccccccccccccccccccccbcbccbbbcccccccccccccccfcccccfcccccccccffcccccccfccccccccffbcccfffffffffffffffffffff
ffffffccccfffffccfffffffffffffcfcfffffcfcfcfcfcccccccccccccccccccccccccccbdbcccbbbbcbbbbbbcbbbccbcbcccccccccccccccccffffcccccfcccfffccfffffcfffffcfffffffffffff
ffcccfccffffffffffffffffffffccbfffffffffccfccffffccffffcccccccfcccccccccccccccbbccccccccccbbbbbbccccccccccccbbcccccccfffcfffcfccfccccccccccffcffcffffffffffffff
ccccccfcfffffffffffffffffffffffffffccccccffccfffffffffffcfcccccccbbbcccccccccccccccbccbcccccccfccccccccccccccccccccffccfcffffcffffffcccccccccccffcfffffffffffff
fffffffffccccccccccffffffffffffccccccccccccccffffffffffcffccfccccbbbcbccccbbbccccccccccccbcccccccbcccccccccccccccffcccffffcfccccfffccccbcccffffffffffffffffffff
fffffffffffccccfffffffffffffffffffffffffffffcfccccccccccccbbbcccccccccccccccccccccccccfcccccccccccccccccccccccccccccccccccccccccccccfffcfcfffffffffffffffffffff
ffffffffffffffffcfffffffffffffffcfffffffffffffffcffcccccccccccccbbbbbcccccccccccccccccfcccccccfccccccccccfffffcffcfffccccccccccffcffffcccffffffffffffffffffffff
fffffffcfffffffffffffffffffcfccffffffffffffffffccfcffffccccccccccccccccccccccccccccfcccbbbcccccccccccccccccfccccccccccccccccccffccccfccccfccfffffffffffffffffff
fffffffffffffffffffffffffffccfcffccfcfffffffffcccccccccccccccccccccccccffcccccccfcfccccccccfcccccccccccccccccccccbcccffffcccfcffffcccffcfcfffffffffffffffcffcff
fffffffffffffffffffffffffffffffffcffffcffffffffcfffffffffccccccccccccccffcccccccccccccbbbddccccccccccccfcfcfcccccccffffffcfccccbffffffcfcccfffffffffffffffffcff
ffffffffffffffffffffffffffffffffffffffffffccffffcccccccccccccccccccccccccccccccccbbccbccccccccbcccccccccccbbbcccfcfffffcffcccccfcfccffcfffffffbcfffffffffffffff
ffffffffffffffffffffffffffcfffffffffffcfcccccccfccccfffffffcccccccccccccccccccccccbccccccccccccbccccccfccccccccffccfcffffffffffffffffccffffffffffffffffffcfffff
fffffccccffffffffffffffffffffffcfcffffffffccfffffffffffcfffcccccccbcccccccccccccccccccbbccffccfcccccfffffffffffffffffffffffccccfcffffcfffffffffcfcccccffccffffc
ffffffffffffffffffffccfffffffffccfffffffffffffcfffccccfcccfccccccccccccccccbcccccbbbbbccccccccccccccccccccccccccccccfccfffffffffffffffffffffffffffcfcffffcfffff
fffffffffffcccccfffffffcfffccfccffcfcfcfffffffffffffffffffcccccccccdbbbcccccccccccccccccccccffcbcfcccfcccccccccbccccccfcccfcccccffcccfcfffffffffcffffffffcfffff
fffffffffffffffffffffffffffffcffcccccfffffffffffcccccccccccfcfccccccccccccccccccccccccccccccccccccccfcccfffffcccffffffcccfcffcccccccfffffffffffffffffcfcfcfffff
ffffffffffffffffffffffffccfcffffffffffffffffffffccccccfccffffffccccccccccccccccccccccccfcfccccccccccfcffffcccccccccfffcfcfffffcfcfffffffffffffffffffffccfffffff
ffffffffffffffffffffffffcffffbfffccccfffffffccccfffffcccccccccccccccccccccccccbcccbbcdccfccbdbccbccfffffffcffcccfffcfffffffffffccffffffffffffffffffffffffcfffff
ffccccccffffffffffffffffffffffcfcfcffffcfcccccccbddcfcccccbcccccccccccccccccccbccccccccccccccccccccffcffffffcffffffffffffffffcfffcccffcccffccfffffffccfffccffff
ffcfffffffffffffffffffffcfcffffffcfccffffffffffcccccccccccffcccccccffccfcccccccccccbbcccccbbbcbbcbcccbbccccccfcfcffcccfcfccffffffffffffffffffcffffffffffffffffc
ccccffffffffffffffffffffffcffffffffcccccfffffffffffcfffccccccbcccccccccccccccfccccbcbfccccfcccccfcccfcfffffccfccfcccccccfcfffcfffffffffffffffffffffffffcfffffff
ffffffffffffffffffffffffffffffffffffffccfcccccccccccfcfffcccccfccccccccccccbcccccccbbcccbbbcccccfccccccfffffffffcfcfccccfcfffcffffffffffffcccffffffffffffffffff
fffffffffffffffffffffffffffffffccffffffffffffffffffffffffcccfccccccccccccccccccccbbbcccccccccccccccccffffffffcccffffffcffcffffffffffffcffffccffffffffffffffffff
fffffffffffffffffffffffffcffcccccffffffffcfcccffffffffffccccccccccfccccccccfcccccccccccccbbbbccbbcccccfcfffccffcffffcfffffffffffffffffffcccffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffcfffffffccffccffffcfffffffccccccccfcccccccccbccccfcccfcfcfcccffffffffffffffffffffffffffffffffffcfffffffffffffcffffff
ffcccffffffffffffcfcffffffffffffffccccfffcfccccfcfcffffcccffffffccccccccccccccccffcccffffcffffffffcccfcfffffffffffffcfcfffffffffffffffffffccccfffffffffffffffcf
ccccccfffffffffffffffffffffffffffffcccfffcccfcccccccffcccfffffffcfcfccfcccfcccccccbcfccbbbbbcffcffffffcbcffcffffffffccccccfffcccccccfffffcccccccfffffffffffffff
`;
            case "image5":
            case "Haunted house":return img`
bbbbbbbbbbbbbbbbbbbbbbbb7bbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
b7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbb
b7bbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbcbbbcbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbcb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbb
b7b77bbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbcfbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbccbbbbbb
b77bbb7bbbb77bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbcccfbbbbcbbbbbbbbbbbcbbcbbbbbbbbbbbbcbbbbbcbbbbbbbb
bb7bbbbb7bb7bbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbcbbffbfccbbcbbbbbbbbbebbbbbbbbbbbbbbbbbbccbbbcbbbbbbbbb
b7bb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbffccfcfffbccbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbcbbbbbb
bb7bb7bbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbffffffffcfbbbbbbbbbbbccbbbbbbbbbbbbbbbbcbcbbbbbbbbbbbb
b7ccb7c7bbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbbbbbbbbbbbbbbbbbbbbbbbbbcefbbbbbbbbbbbbbbbbbbbfecfffffbbbbbbbbbbbbbcbbbcbcbbbcbbbbbbcbbbccbbbbbbbbb
b7cc77bbbbbbbcbcbb7bc7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbebbbbbbbbbbbbbbbbbbbbbbbbccfffbbbbbbbbbbbbbbbbbbbccffffbbbbbbbbbbbbbbbcbbcbbbbbbcbbccccbbccbbbbbbbbbb
bb7c7b7bbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccffbbbbbbbbbbbbbbbbbbbcfecffbbbbbbbbbbbbbbbbcbcbbbbbbbbbcbbcbbbbcbbbbbbbbb
7cc77777cbbbbbbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbebbbbebbbbbbbccbbbbbbbbbbbbbbbbfffffbbbbbbbbbbbbbbbbbbbcfbfffbbbbbbbbbbbbbbbbcbcccbbbbbcbcccccbbccbcbbbbbbb
ccbc7bbbc7bbbbbb77bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbbbbbbcccefffbbbbbbbbbbbbbcbbbccbbbcbbbcccccccbcbcbbbbbbbbb
bcccc7cbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfcfbbbbbbbbbbbbbbbbbbbbeebfccfbbbbbbbbbbbbbbbbbcbbbcbbbbcbcbccccccbbbbbbbbb
cbccbbb7777cbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbfbbbbbbbbbbbbbbbbbbcccfbbbbbbbbbbbbbbbbbbcbbbffcbbbbbbbcbbbbbbbbbbfbcbbbbbbcccccccccbbbbbbbbbb
ccccccccbbb77bbbbbccbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbfbbbbbbfbbbbbbbbbbbbbbbbbbfecfbbbcbbbbbbbbbbbbbbcfeeffcbbbbbbbbbbbbbbcbbbcccbbccbccccbbfbbcbbbbbbcbbb
7ccbbcc7bbbb7bbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbcccfccbbbbbfbbbbbbbbbbbbbbbbbcfcffcbbfbbbbbbbbbbbbbbeceefffcbbbcbbbbbbbbcbbbbbbcbbbfbbbccbcbbccbbbbbcbbbb
ccccc7bbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7bbbcbcbbfbbbecbbbbbbbbbfbbbbbbbcefffffbbfbbbbbbbbbbbbbcccefffffbbbbbbbbbbbbbbbbbbbcbbbcbbbbcccfccbbbbbcbbbbb
cccccccbbbbbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbfbbbebbbbbbbbcffbbbbcceeffffbbeffbbbbbbbbbbbbebbefffffbbbbbbbbbbbbbcbbbbccbbbfbbbcccfccbbbbbbbbbbbb
cccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbfbbfbbbbbbbfcffcfbbbfcfecffbfffffbbbbbbbbbbbcebbbfffffbbbbbbbbbbbbbbbbbbbbbbbcbcbbcbffbbbbbbccbbbbb
ccccccb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfcfbbbbbbbbfccbbbbcfceffefeffffbbbbbbbbbbbeccebffffcfbbbbbbbbbbbbbbbbbffbbbfbbbbbcbbbbbbbbbcbbbbb
cccc7c7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbcffcbbbbbbfcbbbffcceecfcefffffbbbbbbbbbecfbefffffffbcbbbbbbbbbbbfbbbccbbbbfcfbcbcbbbbbbbbbbbbbb
cccc7b7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7fbbbbbbbbfbbbbbccfbbcfcffeeffffccfffbbbbbbbbfcccbbffcfffccbbbbbbbbbbbbbbbbcfbbbbffcbbfcbbbbbcccbbbbcb
cccb7ccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbfbbbbbbcfbbbbccfbfccffccbfffffffffbbbbbbbbfeeebfffffcccffbbbbbcbbcbbcfbbcbfbcccfbccccbbbbcbcbbbbbcb
ccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbebbbbbbbffbbbcffcfcffffefffceffffffbbbbbbfefffffffffffcfffbbbbbcbbebbbcbfccfbbcbcccbbbbcbfcbcbbbbbb
ccc77c7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbcfbbbbbbbbfcbbffffccfefefffffefffcfffbbbcffffffffffffffffffbbbbbbbcbbbbbbcbbfbffbcfcbbbcbfbbbbcbcbbb
cccc7c7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbffbbbfcfcfccefffccfcffffffffbffffffffffffffffffffbcbbccbbbcfbbcbbbcffbfccccbbbbbbbcbccbbcb
cccb7c7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbfbbbfffcccccfffcfffcffcffffffbbfcfffffcffffffffffbbbbbbbbbbcccbbbbbcbbccfcbbbbfbbccbbbcbbb
ccc7cbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbcbbbbbbbcfbbbcccfecceffffcfffffffcffffbbbffcfffeffffffffffbbccbbebfcbbfbbbbbfbbbfcbbbbbccbcbbbcbbbb
cbc777bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7bccbcbbbbbfcbbbbbbbbefbbfcfcffcefffffffcfffffffffffbbbeeffecfffffffffbbbfbbbfbfbbbfbbbbbfcbbfcbcbbbcbccccccbbbb
cb7b77bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbfbbbbbbbbcffffcfeffbffffffcffffffffffffffbbeeffecffffffffbbbbbbbffccbbbfcbbbbfcbfccbbbcfcfccbbccbbbb
7b7c77bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7bbbbbbbebbcbbbbbbffbbbbbbbfffffffceefffffffffffffffffffcffbcefeefffcfffffbbbbbbcfbbbbbbbfcbbffccfcbbcfffccbccbbccbbb
bb777bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbeebbbbbbbcbbbbbbbcfcefcefbffcfffffffffffffffffcffbfcfcefffffffffbbbbbbbfcbbcbbcffcfccfbffcffbcbcbccbbbbbbbb
ccb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbecfbbbbcbbbbbcbbbffcffffffffffffffffffffffffccfccffcefffffffffbbbbccbfcfbbbbbffcfbcfbcccbbcbbbcccbbcbbbcb
ccbcb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbffbbbbcbfccfcffefffffffffffcffffffffffcfffcffeeccfffffffbbbbcbbbfbbbfcbfffcbbffcfccbbbbccbcccbbbbbc
c777bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbccfbbbbbbdbfccfefceffffffffffffffffffffffffffffcbcfffffcffbbbbbbbbfffbccbbcfcbbcffffbcbccbcbcbbbbcbcb
cb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccbbbcbbfcfbbbbbbbbcfffefeffffffffffcfffffffffffffcffffcecfffffcffbbbbbfbbccfcbfbccfbbbfffbbfffbcbccccbbbbcbb
c7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbfbbbfbbbfffbbbbccefcccefffffffffffcfffffffcffffcffcfcffffffffffbbbbbcffcbcfbfbbcfbbbfffcbcbbb77fbbbbbbbbbb
cccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeffbbbcfeffcecffffffffffffcfffffffcfffffcffffffffffffffbbbbbbcfbcccfbbbffbbbcfbbbbbbcbbcbbbccbbbcb
cc7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbccccccecefffffffffffcfffffffffcffffffccfffffffcffffbcbcbcbcfbbfcbbffbbbffcbbbbbbcbcfccbccfcbc
cc7bbbbbbbbbbbbbbbbbbbbbbbbb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffcccebffffffffffffcfcfffffffffffffcfffffffffffffffbbcbbcbccffbbbffbbbbffbbcbcb7f7fbbbccffff
ccb7cbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcfffecbfffffffffffffffffffffffcffffffcfffffffffffffbbbbbebcfbffbbbfffcbffcbbbb7b7ccccbbbfbc7b
cccc7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfccfceffffffffffffffcffffcffffffffcfffcfcfffffffffcbbbbcbcffbcfbbffbeffffcbbbbbbbbbfffcfbbbbb
cbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccffcebfffffffffffffffffffffffffffffffffcffffffffffbbfb7bfffbbcfbffbbbebbfffbbbbbcbbccccfbbbbb
cc7bb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcffcecceffffffffffffffffffffffffffcffffffffffffffffbbbbcccbbbbbbfffbbbbbbbbeffbbbbeefcccccbbbcb
cbcb7bbbbbbbbbbbbbbbbbbbbbbbbbbbebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcceeeeffffffffffffffffffffffffffccffffffffffffffcbbbbbbfbbbcbcffbbbbbbbebbfffbbbcfbbbccbbcbcb
bccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfcfccbefffffffffffffffffffffcffffffffffffffffffffffbbbbbebfbbbfbffbbbbbbbbbbbbffbebfbbbbbbcbbccb
77eb7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccfcefcefffffffffffffffffffffcffccffffffffffffcffffbbbbbcbfbbfcbffbbbbbbbbbbbbffbebfceebbcbbcccb
b7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbebbbbbbbbbbbbbbbbbbbbbbbbbbbfceccccfffffffffffffffffffffffcfffcffcffffffffffcfffffbffcfbfbbfbbffbbbbbbbbbbbbffbbbffecffbbbbbcc
7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcfcceecefffffffffffffccffffffffcffcffffffffffffffcfcffbbbbbeffbfbbffbbbcbbbbbbcffbbefbfffccfbcccc7
bcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeffcfcfcffcffffffffffffffe4f2ffcfcfffffffffffcffcffffbbbbbbbbffcbbffbbbcbbbbbbfccbffbbfcbbbbeffbbe
7cc7bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbfcfeffffcffcffffffffffffff44f44cfffffffffffffffcfcfffffbbbbbbbbffbfbfcbbccbbbbbffbefbbecbbbbbbbebcb
7cbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffcccfcffffffffffffffffffff44f44ffffffffffcffffffffffffffbbbbbbbbffcbfffbffbbbbbffbbfbbffbbbbcbbecfb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbebbbbbbbbbbbbbbbbbbccffcfcfffffffffffffffffcf2ff4444fefffffffffffffffffffffffffbbbbbbbffbbcffbbbbbbbffbbffffcbbbbbbbfebb
eebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbfffcffffffcfffffffffffffffffe4fe44cefefffffffffcfffffffffffffffbbbbbbbccbbffbbbbbbbfffffffbbbbbbbcfebcc
beebbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbfffffffffffcffffffffffffffffe44ff4efe4ffffffffffffffffffffffffcffebbbebfbbbffbbbbbbbbfffbffebbbbbbbffcbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbebbbbbcbbbbbbbbbbbbbbbbbcccffffffefffffffffffffffff444ffefff4efffffffcffffffffffffffffccbbbbebfbbbffbbbfccbbfffeffcbbbbbbbfbbbb
bebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbbbbbefcfffffffffffffffffffffffffe44eeff4f44fffffffffffffffffffffffffbbbbbfbfbbbffbfbebbbbbefffffbbbbbbbcbccc
bbbbbbbebbbbbbbbbbbbbbbbbbbbdbbbbfbbbbdbbbbbbbbbbbbbbbefccffffffffffffffeffffffcffff4f44ff4f4fffffffffffffffffffffffffbbbbbbbffbbbffcbbbbbbbbbbbbfffbbbbbbeccbb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbdbbbbbbbbbbbbbbbbbbbbffcfffffffffffffffeffffffcfffe44fefffee4fffffffffffffffffffffffbbbbbbbbffbbbffbbbbbbbbbbbbbbfffbbbffbcecb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbedddbebbbdbbdbbbbbbbbbbbcfcfffffffffffcfccfeffffffcfff4f44efce4fefffffffffffffffffffffbbbbbbbbbbbffffffebbbbbbbbbbbbbfcfbbcbbeebbb
bbbbbebbbbbbbbbbbbbbbbbbdbbbbddbbbbbbdbbbbbbbbbbbbbbfcffffffffffffecfeffcffffffcfff44f44ff4f44ffffffffffffffffffffbbbbbbbbbbbbffffffbbbbbbbbffbbbefffbbcbbeeebb
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcdbdddbefbbbbbbbbccbbffffffffffffffeffeefceffffffcfff44f44fc4e44fffffffffffffffffbbfbbbbbbbbbbbbbbfffffbbbbbbbbffbbffeebfbbbeeebb
bbebbbbbbbbbbbbbbbbbbbbbbbbbbbbbcddbbbfbbbbbbbcfccffecfffcffffffefeeefcfbffffffefffffffffccf4effffffffffffffffbbcfbbbbbbbbbbbbbbbcfffcbbbbbbffcbfffbbbfbeeebeee
bebbbbbbbbbbbbbbbbbbbbbbbbbbbbdbdebbbbbbbbbbbffefffcfffffbffffffeffebfeceffffffefffe4f4eff4fffffffffffffffffffbdfcbbbbbbbbbbbbebbebfffbbbbbfffcfffbbbbfbbbbbbee
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbdebbbbcfbffbeffffffbfffffffcffeeecceffffffcffff4e44ff4f44ffffffffffffffffbffdbbbbebbbbbbbebbebfffffbbbccebffbbbbbfbbbbebee
bebbbbbbbbbbbbbbbbbbbbbbbbbbbbbddbcbbbcbbeffffffbffcffdbcfffffeecceecefeeffffffcffffff4eff4444ffffffffffffffffffcdbbbbbbbbbbbbbebbbbeffffbbcbbffbbbbbecbbbbbbef
bebbbbbbbbbebbbbbbbbbbbbbbbbbbbbdbdfdfbbffbcfffbbffbdebbfffffceefe2cceeebffffffccffefffefcef4ffffffffffffffffffbbbbbbbbbbbeebbbbbbcbbbfffbfbbbffbbbbbfbfffffcff
bbbebbbbbbbbbbbbbbbbbbbbbbbbbbbbbebdbbfffffcbbfcffbbbfbfffcffcecfe2efefebffffffffffe4f44ff4f4fffffffffffffffffbbbdbbbbbbbbbebbbbbbfbbbfffbbbbbfffbbbffbffbfffff
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdeffcfbfbbfbdfbbfbbbfffccecefcfc4cfffebffffffffcffff4eff4e44fffffffcffffffffcbbbbbbbbbbbbbebfcbfbbbbfffbbbbbbffbbbffbfbbbbfbf
bbbbbbbbbbbbbbbebbbbbbbbbbbebbbecfffbbbcbfbbefbbbbccbbfffbcccffcffecfefebffffffffffffffffcee44fffffffffffffffffbbbebddbbbbbbbbbbffbbbbfffbbbbbfffbbbbfeefcbbcbb
bbbbbbebbbbbbebbbbbbbbebbbfbbffbbbfbebbcccbbbfebbbcfbbbfcbbeffffceecfbfeefffffffffffff4fffffefffffffffffffffffbddebbbbbddebbbbbbfcbbbbfffbbbbbfffbbbbffecebbbbb
bbbbbbbbbbbbbbbbbbebbbbebbfbbbbbbfbbbebcfcebdfccccfbbbbffbbcffcfceefffeebfffffffffffee4eff4f4fffffffffffffffffbbdebbbbbdfdbbbbbbfcbbbbfffcbbbbfffbbbbffffbbbbbb
bbbbbebebbbbbbbbbbbbebbbebbbbbbbfbbbecbcffffffbbfccbdbbeffbffeeccfefffceecffffffffffffffeffee4ffffffffffffffffbddbbbebbebbbbbbbbefcbbbffffbbbbffffbebffffbbbbbb
ebbbbbbbbebbbbbbbbbbbbbeeebbbbefbbbfbeffdbddfbbbeffbbbbbbffcceefc4ccffeeefffffffffffffffffffffffffffffffffffffbdbdbdbbfdbbbcbbbbbffffffffffbbbefffbbbfffbbbbbbb
bbbbbbbbbbbbbbbbcbbbbbbbeeebbcbccfffbbbbddddcbbbecfcdbbbbffceeefceecffeebfffffffffffffffffffffffffffffffffffffbbddbbbdfbbbbebbbbfdbffffffffbbbbbfffbccfbbbbbbbb
bbbbbbbbeebbbbbbcbbbbbbbebbfbeebbbfbbbbbbdddbfbbbcfcffebffdfeeefefeefffeefffffffffffffffffffffffffffffffffffffbddbdbbbcbbbbbbbbfbbbbbfffffffbbbcffffcfbbbbbbbbe
bbbbbbbbbbbbebbbfbbbbbbefcbbbbebbbbbbbbbdbbdddfffffffccdffbfecefefceffeebfffffffffffffffffffffffffffffffcfffffbddddbbbebbbbbbbbebebbbbbbffffbbbcfbffffbbbbbbbbb
bbbbbfbbbbbbbebbfebbebefebbbbbbbbbbbbbbbbebdddbbbbbbbcfbfcbfceefefccfeeebfffffffffffffffffffffffffffffffffffffbddddbddfbbbbbbbfbbbbbbbbbbffffbbffbfffbbbbbbbbbf
bbbbbbbbbfbebebbebbbefbbeeebbbbbbbbbbbbbbbcbcbbbbbddddfffcbffeeffcfcececeffffcffffffffffffffffcfffffffffffffffbdddddbffcbbdfffebbbbbbbbbbfffffffbbfffbbbbbbbbbe
bbbebbbbbbeebebbebbbebbbbbbebbbbbbbbbbbbbbbbbbcbbbfbbdfffcbcecefccfeeecceffffffffcfffffffffffffcffffffffffffffbdbddddeefffcfcfbcbbbdccbbbbffffffbffffbbbbbbbbbe
bbbbbbebbbbbbeebecbbbebeeeebbbbbbbbbbbbbbbbbbbbfbbcbbfddcfdcecefceffefecefffffffffffffffffffffffffffffffffffffbddddbddffffffcfbbbbbbbbfbbbfffffffffffbbbbbbbbbf
bbbbbbbebbbcbeebebbbbbeeeebbbbbbbbbbbbbbbcbbddbbdfbdfddbefffecececefceffefffffffffffcfffffffffffffffffffffffcfbdddddbdcffffffffbbbbbdddbbbdfffffffffbebbbbbbbff
befebcbbbbbbbbebbbebbbbeeeebbbbbbbbbbbbbbbbdbdecefcfbddbdffeeceeeeceffffbffffffffffffffffffffffffffffffffffffccdddbffbfffffffffffbbbbbbbdbdfffffffbbbbbbbbbbbbb
bbbbbbbbbbfefbbbbbbebbbbebbbbbbbebbbbbbbbdddddbdbcccfffcdffeececfeeffecfefcfffffffffffffccfffffffffffffffcffffdddddddfffffffcfffedbbbdbddbbffffffbbbbbbbbbbbbbe
bbbbbcfcbbbfbbbbbfee44444444eebbbebbbbbbbbfddddbbbfcfdddffbbeeceeeffefffefffffffffffffffffffffffffffffffffffffdddfddddffffffbfffbbbbbdbbddbffffffbbbbbbbbbbbbeb
bbbbbbbbfbebbfeb44f44444444444444ebebbbbbbffddbbddbcfdddffdbefceffceffeeefffffffffffffffffffffffffffffffffffffdbdedddfffffffbfffbbdbbbdddbbffffffebbbbbbbbbbfff
bbbbbbbeebbbbfe444c4444444444444444ebbbbbffffdbddfefcdddcfbbeeefcecfffeeffffffffffffffffffffffffffffffffffffffddffcfffffffffedcffbbbddddbbbdffffffbbbbbbffbbcce
bebbbbeeecce4f4f44f444444444444444444bbeeffffbdbdebffdddffccecfeeffcfeeeeffffffffffffffffffffffffffffffffcffffddebfffffffffffddfdbddbbddbbbbffffffbbbbbbfcbbeee
bebbbbbbee4444ef44e44444444444444444444ebefefbddddfcfddddfcfefeeffeeefeeeffffffffffcfffcccfffcffffffffffffffffdbfcfffffffffffbbdbdbebbddddbbffffffbbbbbbebbbbee
ebbbebbe4444444f4444e4444444444444444444befcfbbddddffcdddcffeefeffeeefeeeeffffffffffeffffecfffffffffffffcffffcffffffffffffffffdbbbdbdbdddbbbffffffbebbbbbbbbbee
bbebbbe44444e44f44f4e44444444444444444444eccfefddddbcfffecffefeeefeeefbeeefffffffffcffffcfffffffffffffffcffffffffffffffffffffbbbbdbbffcffbbbffffffbbbbbbbbbeebe
ebebbb444444444e444e4444444444444444444444fffbffeeebefffffbcecceefeeefeeeffffffffffcffffffffffccfcffffffffffffffffffffffffffffbebbdbbdbddfffffffffbbbbbbbbbbeee
bbbbb44444444444f44f4444444444444444444444ffffbfffffffffffeccfffeeeeefecefffffffffffffffffffffffcfffffffffffffffffffffffffffffbddbbbdbbdddbeffffffdbbbbebeeeeee
becb44444444f4444f4e4444444444444444444444ccfffffffffcfffffffffffececfeeecffcfffffccfffffffffffffffcffffffffffffffffffffffffffebddddbbbbbbbdcffffffdbbbfbebbeec
beeee4444444444444f44c444444444444f444fe4eceffffffccffffffffffffffcecfeebcffffffffcfffff4fffffffcfcffffffffffffffffffffffffffffdddddbbdddbbbcfffffffdbbbbbeeeef
eee44e444444ee4444e44e444444444444effffffffffffffffcfffffffffcfffffeefecbcfffffffcfffff44e4ffffffffffffffffcfffffffffffffffffffdbbdddbbbbfdbdfffffffebebbeeccec
eb444444444444f4444f4f444444444effffffcffccffffffffcffffffffffcffcfeffefeffffffffffffff44e4efffffffffffffffcffffffffffffffffffffbddbcebfbbbbbfffffffffbbbbbcfeb
ee4444e444444e4f4444ff444444444e4ffffffffffcefffffffffffffffcfcffffcefefefffffefffffffef4eeefffffffffffffffcffffffffffffffffffffbdddbebbdbdbbbfffffffffbbbbbeee
e4444ee4444444ef44444f4444444444fffffffffffffccfffccfffccfffcccfffccefefecffffffffffff44fefffefffffffffffffcffffffffffffffffffffdddbccebbbbbddbcfffffffbbbeeeef
e44e44444e4444e4e4444f444444444ffff4fffffcfcccceeefcffffccfcffcfceecefeceffffffffffff2e4ecf22effffffcffffffcfffffffffffffffffffffbdbfcfbbbbbdbbbfffffffebbeeeee
4444444444e44e44ef4444f4444444f4ff44efffffefcceecccccffffffccfcecfffecececfffffffffff4e4eff44fffffeffffffcfefffffffffffffffffffffdddfffbdbddbbbbbfffcfffbbeeeee
4444e444f4444444f44444ef44444444ff4e4fffffffeeeecccfffffffccfffffffcefefccfffffcfffff44ffc444cfffffffffffefefffffffffcffffffffffffbddffbbbbbbbbbbbfffffcebeeecc
44444e444c444e44e4444444f444444ff444efffffefeffcfcfffffffffffffcffcecfefecfffffffffff44feeecfeffffffffffffffffcfffffffffffffffffffbffffcdbbbbbddbbfffffffefeeec
e444444e44ee44444e4444444fff44f444444ffffffffecccfffffffcccceeeeefcceeceecffffcffffffe4eee4444fffffffffffffffffffffffffffffffffffffefffcbddbbbcbbbbffffffffeeee
444444444eee44444f44444444ff444444444fffffffceefceeeecccccfcccfefccffeceeeffffcffffffeeefcee44efffffffffffffffffffffffffffffffffffffffffbbdfcfbbbbbfffffffceecc
4444444444fefe444ee44444444f44444444efffffffcceeefccfffcccfcfffceeecfffecffffffffffffeefceee4eefffffffffffffffffffffffffffffffffffffffffbbdfebbbbbbfffffffffccf
444e4444444e4ee444ff44444444fe444444efffffffffffffffffccfcffcfcfeefceffeeffffffffffffefccfef44efffffffffffffffffffffffffffffffffffffffffbbdfcbbbbbbefffffffeefc
444444444444eeef444ff44444444f444444fffffffffccccccccfcceffffffcccfeeeceefcffffffffffffcfeeeecfcfffffffffcfffffffffffffffffffffffffffbffbbebdbbbbebbffffffffcfc
44e444444e444444fcfff4444444ef44444fffffffcfffccccccccccccccfffccffffceccfccffffffffffffffffffffffffccfcfcffffffffffffffffffffffffffffffbbbbbbbbebbebffffffffce
44444444444444444eff44444444e4444444ffffffffffcffffcfeeceecccfceecfcfcfffffefccffffffffffffffffffffffeffffffffffffffffffffffffffffffffffbdbbbbbeeeeeeefffffffce
f444e4ee4444444444eff44efc44f4444444fffffffffffeecfeeeeeeecfcfffcccecffccffffcffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffdbbbbbeeeeeeeefffffffce
4e44444ee4444444444ffffffffff444444efffffffffcfeeefcfffcffffffcccccceccfeefffffffffffffffffffffcfcffffffffffffffffffffffffffffffffffffffbbbbbbeeeeeeeeeffffffce
44444e444f444444e444ff4444efff4444eefffffffffcffffeecceeefcecfceccecffffeefcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbeeeeeeeeeeefffffffe
f44444444fe44444e4444444444efffffffcfffffffcffffffccfeeeeccffffeefffccffbfffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffbbbbbeeeeeeeeeeffffffe
4444e44e44efe4444444444444444ffffffffffffffccffffbecffffffccceeecffeecffbffffffcfccfffffffffffffcfffffffffffffcffffffffffffffffffffffffffebeebeeeeeeeeccffffffc
f444e4444444eff4444444444444fff4444efffffccfefffcceebbeeffeccfccfcfcfcccbcffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffeeeeeececcccccfffffff
44444444444f44f4444444444444ff44444ffffffcecccefffeeefffffeecefcefeecfeebccffffffffefffffffffcfffcfffffffffffccffffffffffffffffffffffffffffeeeeeecececcccffffff
ff444f44444e44ff4ee44444444ff444444efffffceebefecfffffffffcffeffffffccecbeeffffffffcfffceeecffffffcfffffffcffcfffffffffffffffffffffffffffffceeceefcfccfcfffffff
4f444444fffee44ffffe444444fcf44444effffffebefecececebeeefccecffeeeccecfcefffffffffffffffffffffffffffffcceccffffffffffff4ffffffffffffffffffffeeceefcfccffcffffff
4f4444444444f444444ffeeeffce444444ccfffffcfcffcceceeeeeeeceeccfcfcfffcefefffffffffffffffffffffffffffffffffccffffffffff444ffffffffffffffffffffccccfecccfcfffffff
fe4444444f44fe44444ffffefe444444444ffffceeffefefefeeeeeeccefcffceefceeffcfffffffffffffffffffffffffffffffffccffffffffff4444ffffffffffffffffffffcccfcfcfcffffffff
4444444444ecfffceff444444444444444effffcfcffeeeccebeccfcebeeeeeeeeeeeceeffffffffcfffffffffffffffcfffffcfffccffffffffff444fffffffffffffffffffffcccfcccccfcffffff
4fe44444444444444444444444444444ffffffcfceeeccefffeffeefeffccccceffeeeeeecefffffffffffffffffffffffffcfffffccfcffffff4fe44feffffffffffffffffffffcccccfcccfffffff
4e444e44444444444444444444444444fffffcfefceeeefecccfffefeeccfebbeeeeeeeefcfffcffcfffffffffffeeffffffffcfffcfffffffff4ff44fffffffffffffffffffffffcccccffccffffff
4e444e44444444444444444444444444fffffecffeffefeffffffffffeeeefeeeeeeeffffcfccecfffffbeeeeeeffffcffcfcccceeffffcfffff4ff4feffffffffffffffffffffffffcffccccffffff
4f444e4444444444444444444444444ffffcfffcffefeefffffffffefffefffefccfffecccffffffffffffffcccffffffffffffffffffffffffffffef2cffffffffffffffffcccfffccffcfcccfffff
4f444e444444444444444444444444effcffffffceeeefffffffffcfffefffffefffffffcffffffffcfcffffffffffffffffffffffffffffffffe24ff2eefffffffffffefffccccfccccfcffcffffff
ff444f44444ee4444444444444444fcfffcfccffcceeefffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffff44ff4fefffffffffffeffccfccfcfcccffffffffff
ef444e4444e44444444444444444eccfffcceeefeffffcffffffffffffffffffffffffffffffffeecffffffffffffffffffffffffffffffffffff2eff2f2ffffffffffffffcccfffcfffccffcffffff
ef44f44e444f4444444444444444ffffffccccffeffffffffffffffffcfffffffffffffffcffffcffffffffffffffffffffffffffffffffffffff2fff2fffffffffffffffcccfcffccccccffcffffff
ef4e4444444fee444444444444ff44ffcffefcfffffffffffffffffffffffffffffffffffeffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfcffffffffffffcfffff
efef444444ef4444444444444f444effcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffe4fffefcfffffffffffffccccfffffffffcffffcfff
efef444444ff44e444444444e44cfffcfcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeefff4e4ffffffffffffcfcffcfffccccfffcffffff
efefc4444efffc4444444444f4efffcfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffeeeffffffffffcffcfffcffffffffffcffffff
efcfee4e44fff44444444444444ff44efffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffeffffffffffffccffffcfffffccfffffcfffff
efcceeefcffffe444e44444444ce4444ffffffffffffffffffeceffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffeff4ffffffffffcfccccfccfffffffcffcfffff
eccceeefffffff4ec4c444444ee444e444cffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffee44fffffffffffcccccfcccffffccfffffffff
cccceefffffffeff44444444ee4444f444fefcfffcfffffffffecfffffffffffffffffcffffffffffffffffffffefffffffffffffffffffffffceeffeffcffffffffffffffffcffffcfffffffffffff
cccceeeccfffffce44444444444444c444eefcffeffffffffffeffffffffffffffffffffffffffffffffffffffeecfffffffcffffffffffffffceffffffffffffffffffffffccffcfffffffffffffff
fffcccefffcffcffffef4444e444e4c4f44efcff4ecffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefeffef24fffffffffffffffccffcfcfcfffffffffff
cfcfccffffffffffffe44444e44444eec44effff4eefceffffeffefffffcfffffffffffccffffffffffffffffffefffffffffffffffffffffffefeff4eefffffffffffffffffcffffcfffffffffffff
ffefeccfffffffffffceeeeeeeeeecfffeffcfcf444feffff2efffffffffffffffffffffcfffffffffffffffffee4ffffffffffffffffffffffcfeffefeffffffffffffffffffffffffffffffffffff
ffffcfffffffffcffceeeecceeeeeeefcfffeccfe44fcffff4e4efffffccffffffffffffeffffffffffffffffffffffffffffffffffffffffffcccfffffffffffffffffcfffffffffffffffffffffff
ffffccfffcffffccceeccecfcceeeeefffcfcfeffe4ccffff4e2ecbffffffffffffffffcecffffffffffffffffef4ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ccfffcfffffffeccfffececfecccecccceecefeff4efcefff2eeecefffffffcfffffffffe4ffffffffffffffffeeefffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
ccffcfffffffccccfcffffefccceeeccfffcefef44ffcefff444ecefffffffccffffcffffefffffffffffffffffcffcffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffcfffffcccfcffecffcecfceeeeefffffecefe4feecffeee4efffffffffceffffefffeeffffffffffffffffffffeffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffcffffececcccfcecccccfeeeeeeffffceeef4eeeefffff44fcefffffffccffffffffecffffffffffffffffe44feffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffcffcffffeffcfefefccfcefcceeefcfffeeeeefeecffffe44febfffffffcfffffffffefffffffffffffffffe42ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffcffcffcefcccecefffececceeeecfcffffecf4eefffffe44eebffcefffffeffffffcecfffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffcffcecceeefcceeeeeeeeeffcffffccf4eefcfffe244eefffcfffffffffffffffeffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffcffffefcceccceeefffcfceeeeeffffffceefefefeffefe44eeffffffefffffffceccfeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffccccffffeceeecfffeccccecffffffeeefeeeceffffee4efffffffcfffffffefffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffcccccffceeececceceecccefcfffffefee4ffeeefff2e2ecfffffefffcfffefffccffffffccffffffffffffffffffffffffebbffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffcfffffceeeceeefceeecfcfccffffffcfeeeffeccfffeeeccffffffffffcefffffefeffffffffffffcffffffffffffffffffcffeeffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffcffcfcfeffececfccfffffffffcebfefefcffcbeefffffffffcfffffffffececffffffffffffffffffffffffffffeffffffefffffffffffffffffffffffffffffffffffffffffffffff
fffffffffcfffceeeefffcffffffffcfffffffcebfecceeefefeffcfffcffecffcffffffffebfffffffffffffffffffffffffffcffffff4eeffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffcfffcfffcccffffffffffffceeefffeceffececfeefffffefffcffffffffe4ffffffffffffffffffffffffffcffffffffbfefffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffcfffffffffffffffffffffffffeeeffecfcfcfffffeccfeffcfffffffffcfeebffffffffffffffffffffffffffeffffffffcffeffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffeefffeffcffffcffeeefffffffffffffffffefffffffffffffffffffffffffffcffffffffcffeefffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffcffffffffffcffeccfcfffcfffccffeeffffffffffffeccffffefefffffffffffffffffffffffeffffffffffefeefffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffcfeefefffffffffcfffefcfffffffffffffffefeeeffffffccffffffffffffffffeffffffffffefefcffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffcffefeefffccffcecffeeffffffccffceffffeeeeeefcffcfcffffffffffffffffeffffffffffefcfcffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffeffffffeefffffffcfffeffefffeccccfffefefeeffccfecefcfffffffffffffffffeffffffffffcefffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffefeeeffeccfffffcefefefcefffceefccfffffceeeeeeeccccceffffffffffffffffeefffffffffebbfcbfffffffffffffffffffffffffffffffffffffffff
ffffffffffffffcfffefffffffffffffffefeeccfccfcfcffffefeceefffeececfcfffeffecfefcfcfffffffccfffffcffeeeeefffffffffebbbccfffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffeffffffefffffffceefeefcccffeffcefefffcfcfcecccfcfffcfcceefffcfffeffffcffffffffffeebfeffffffffceeebfffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffeffffffeeffffffffceeeffcfcfecfcccefffefcfeeefcfcfffcfccccffcfffcfcfffcffffcfffffeeeeffffffffffeeebfffffffffffffffffffffffffffffffffffffffffff
ffffffcffffffffffeecfffffeefffffffffecccfcffcefeffcffffeccfcccfcecfffcffccfffccfcffcfffcffffffffffceeefffffffffeebbbfffffffffcfffffffffffffffffffffffffffffffff
fffffffffcffcffffeecfffffbefffecffcfeffcfefffffccfcfffffceffcecccfffcfccfcfccffffffefffcffffffffffceeefffffffffbeebcfffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffeefefccfeefffefffffefcefcffcffcfccffffcecffccccefffccfcffffffffcffcffffffffffffffceeefffffffffebebeffffffffeffffffffffffffffffffffffffffffffff
fffffffffffceeffceecefccfeeffeeffffffffccffefffcfcfccffcccfcfccffffefffffcffcefffcfcffffcffffffffffceeffcbbebeeebeebffffffffbffffffffffffffffffffffffffffffffff
ffffffffffcffffceeecefcefeeffeefffecfffcccfecffefeffeccecfcccfceffceefcfffccceeffffcffffefffffffffceeffffbbebfeebbbbffffffffcffffffffffffffffffffffffffffffffff
ffffffffffefcffffeeccfeeeceeeeeeffcefffccffefffffffcffccccffefccfffcefccffffceeffffffffeeefffffffffcfefffebbbdeeebebffffffffcffffffffffffffffffffffffffffffffff
ffffffffffcfffcffeeeeffcfeefffffffeeccfcfffeffeeffcccfcffcffcfeefceeefcfffffceefcffffffeeefffffcffeeeefffcceecfeebcbffffffeefffffcfffffffffffffffffffffffffffff
fffffffffffffcfcceeecffcfeeffeefeeeeecfcfffcffefeffccffcffccffcefeceecefcccfceeffffffffeeeffffffffeeeefecbeeeeefeefeffffffbffffffffffffffffffffffffffffffffffff
ffffffffffffffccceeecffcfeeffcefffeeffffffeecfefeffccffeffceffeefeceeeefcfffceefcffffffeeefbffffffcbfefeeeeeeeefeeeecfffffeffffffffffffffffffffffffffffffffffff
fffffffffffcffcccefececcceecfeefffeefffffccecefcfffeccfffcecfcfeeeefeeeeecfeeeebeefcfeceeefffffcffeeeeffffcceccfebbfffffccefffffcffffffffffffffffffffffffffffff
ffffffffffccfccfeeeceefcfeeececfffeefefffeefecfefcfffefefefffcfeeeefeeccfbfeeebeccffffcbfeefffffffeeeefbbeebbceeeeefffffcffffcfffffffffffffffffffffffffffffffff
ffffffffffffffefeeeccececeeeeeefffeefeffcfefeccffefffceffcffcecfffffeefcfffffeeffffffffcfeceeffcffcfbefeeeeeebceeeefffffffcffcffcffffffffffffffffffffffffffffff
ffffffffffffffeccfceeececeeececfffeefefccffcffcffeffccfcefffcffefeceeefffffffeefcfccffceefeffebfffffeebbeeeeeceeeeefcfffffeffccfccffffffffcccffffffffffffffffff
ffffffffffffffffefceeeeeeeeeceefffecfffcccccfefcfcffeffffffffeceeecebefcfffffeeffcffffceefeffffffffcefeeeceeeceeeebfccffffeffccffcfffffffceffffffffffffffffffff
ffffffffffffffffefccecceebeeceeefffccffcccfefefefbfefcfefffefececcfeeefcfffffeeffffffffeefffffffffffeceeeeebceeeebbfffffffeffefffffffffffeffffffffffffffffcffff
ffffffffffffffffefeeeeeeeeeeceecececeefffffcfefefefefefefffcfecefefeeefffffffeeffffffffeeffffffffcebeeeeceeeeeeceeefffffffefccfffffffffffffffffffffffffffffffff
fffffffffffffffffcceeeeeeecceeeebbbeceebbffffefffffecefcfcfffcccfefeeefffffffeecfffffffeeeffffffffeebeeeceeceecebeefffffffefcfccfffffccefffffffffffffffffffffff
ffffffffffffffffffeeeeeeeeefecfffefffffcffffcccffffefecefcccfceefefeecfffcfffeeecffffcceccffffffffefceeeeebeebeeeeefffffffefccccffffffcffffffffffffffffffffffff
ffffffffccfffffffffceeeeefeeeeeeeeffcffcfcfffcecccccfefcfefceeecfefeeefcffceceecfffffffeecffffffbbeeeeeeeeebeecebeefcfffffefcffcffffffcffffffffffffffffffffffff
fffffffffcffffffcffefeebeeeeeceeeeeeeffffeeeeceeeefeccccfecceeecceeeeeefffeecccccccfffeeeefffffeefcceeeeeebebeebfffcefffffeffccffffffccffffffffffffffffffffffff
ffffffffffffffffffcfffffceeeeeecbefeefcefcccebeeeecefeeecccccceeeeeecfffeeeccffeccccfcecfefffffeceefeeebbbeccefcffecefffffefccfffffffffffffffffffffffffffffffff
ffffffcffeffeffcffffcffeeeeecbbeebbeeefffcfebbeeffefefeeeecefeeeecccffeeceffeeeffcccecceeefffffeeeebeeeeeeebeececceffefffffcfffcffffffffffffffffffcffffffffffff
fffffcccffffceffffccfffffffffeebeeebbbbffeeffffffcefcfceeeeeeeefceeeffeecfeefccfffffcefffeccfeeefeeeeebeefefeefeceeffffffcfffffffffffffffffffffccfefcfffffcffff
fffffffcffffffffcfffffffffbbbbbebbbbebbbeeeebefcfffcfeecfeeecefffcffccefeefcfffffeeecffffeebbbeeeebbbeeceeeceeceecececffcfffcfffffffffffffffffceeeeefffffffffff
ffffffffffffffffffccffffffbfcbbbbbbbebbbbbbeeeeefceeffccceffffcfcffeeeeeecceffeceefccffeeeeeeeebeeeeebeeeeeceefeeefffffcccfffffffffffffffffceccecccecffffffffff
cffffffffffffffffffffffffcbfffffe4bbceeeeeeeebebbeeeecccfcefcceeeceeeceeeeffcfeeecffefceeceeceeeeebeeebeeeefeefeeecfbbecebbbefefecfffffffeecefeecffffffffffffff
fffffffffffffffffffffffffffeefbedebbbbbbbbeeeeeeeebbebbeeeeeeeeeeefceccffeeeeeefcfcefcceebeeeeeeeeeeeeeeeeeeefeeeecefbfeeecefffcfccfffffcceccffecffffffffffffff
ffffffcfcffffffffffffffffeecfeffefcfcbbbbbbbbbbbbbbeebeeebeeeeeeeeeccfcefffcfceceeffcceeeeeeeeeeeeeeeeeeeeeeeefcfcffecfffffcfffcffcffffcccfcfffffffffffffffffff
fffffffffffffffffffffffffffffefebfeffcfbffbbbeccbebbeeeeeeeeeceecceeeeeeeecfccfeefeeeeebeeeeeeebebeeeeeececeeceeecfeeeecfefffefffffffffffcfccffffffffffffffffff
fffffffffffffffffcffecfffffffeccbfeffbfebfbfccbeeecfeeebeeeeeeeeeeeceeeeeeeeeeeeeeeeeeefceebbebbeeeeefceeeeeffffffeeeeceeeeeefffccfcffffffcffffcfffffffffffffff
fffffffffffffffffffffcffffffffffbfbff4feffbeccfefcefceceefbee44444beeeeeeeeeefcebbebbebbefbececeeecbeeeeefebeeceeeecffeeeceefcfcffffffffffefffffefffcfccccccfcf
fffffffffffffffffcfffcffffceeffceffffbfecfecfefeffecefccfeffccffe444444444bb444eeeebebbbeeeeeeeeeeeeeeeeeeeeeeceeeeefeffeeccffeffcffffccccffffeccffcccecccfcffc
fffffffffffffffffffffccceefffeeeefeffcfffffffecbffeceeeffebfffeecfe444c4eeeeebeeeebbbeeeeeeebeeeebbeeeeeeeceeeeecfffffcffcffcefeefcfcccccffcefccfffffffccfccfff
ffffffffffffffffffffccffffeeeffeefeffcfeefcffefffeffcefcfccffefffffefeeeebe4444444bbbeebbbeeebeeeeeeeeebbeeececeeccfccfffcecfcefcffeceeefccfefcfffcfffffccfffff
fffffffffffffffffffffcffcfffffececeffcfeefeffefcfeccffffcfcefccfcffecfefffeee44444444bbeebbbbbeceecceeeeeeeebeeecebeeefffffcfefceeccefefffcfffffffcfccffcffcfcf
ffffffffffffffffffffffffcffffffefffffffccfcffffefcfffeccffcfefcfffceefccff4e4e444444444bebbbbbeeeeeeebbeceeeeeeeeeceeeeeceeeffccfffceefffefffffffffeefcccccccfc
ffffffffffffffffffffffffffffffffffeefeceecefccfffeefffcffffeeceecccfecccfffffcfc4bdd4444bbbbbebbbbebbbbeeeeebbeeeecefebcecffffccceeeeeefffffcffceecefffcffffffc
fffffffffffffffffffffffffffcffffcefceccececefceececceeffffeeecffffcccffcefeceffffffeffbbbbbbbbbbbbbbffbbbbceecbeebbebfeefceeceeeecceefceccefcefbeccecffffffcffc
fffffffffffffcfffcfffffffffcfffffcccfcceeeecefeecffeeeceeeffccfcffcffffffffffefeeccceeeeeeeeebbbbbbffefbbbbbbeebeebeeeeeeceeeebefeecbecffbfecefeccffcffcfcccffc
fffffffffffffffffffffffffffcffffcfccefeeeeeeeececefeececfeefeccfccceecfceccfcffeeeebbbeeeebbbeceebeffffcbbbbbbbbbeeeeeebeeeeceeeeebeeeeeebecfceffcfcfffcffffcff
fffffffffffffffffffffffffffffcccecefefceeefcffffcfcfcefcceeeeeeeccfeefffcecfcfffcecffeffeeeeebbbbbffcfefbbbbbbbbbbbebbeeeeefcfeeeeeeebbebffeeffefcfffffcfffccfc
ffffffffffffffffffffffffffffffffcceefefbbefeeccecfceececfceeeececcffcfffcefffcffbbe4e4bbbbbccebbbbfffcffbeeeebbebeeeeeeeeefeffeeeeebbbeeeeececffecccfffeeecefff
ffffffffffffffffcfffffffffffffffceffffceeccccebcccccbfeceeeeccecceefcecfffffefececc44bbbbbbbbbeebbfcffffbbbbbbfbebbbbbbebfcffffebbeeeeebbbeeeebcccceeffefceefff
ffffffffffffccffffffffffffffffffffeecfeccffeeeccceefcfffffcceeeccceeceeceecfccfefebfeeefebebbbbbbbffcffebbbbbcfbbbbbbeeeeffffffeeeeeeebeeeebbeeeeeeecfceefcffef
ffffffffffffffffffffffffffffcfffffcfebeeeeeeecccecfcfefccffceceefceffeecfcceeeeeeebeffffffeebbeeebfffffcbbbbbefbbbbeebb44ffffffbbeeeeeeeeeeeeceeeeeeebecceeccff
fffffffffffffffffccfffcfcccffcfffffffeecfffeefeeecfeefcfffffcfeecffeeeeceeffcceffeeeeebe4ffbbebbffffcffffcbbbefbbbbbbbeeeffffffbbbcbbeebeeceeeeeeeecbcceeefcccf
fffffffffffffffffffecfffffccffffffffcfeebeeeeeeeccceceeefeffceffeffeeeeeeeeeeeeeeefeceebbb444becfffccffffeebbffffbbbbbbbbffffffbbbbbeeebeebeebeeeeeebebecfceecc
ffffffffffffffffffffffeffceffffffffffcfeeeeefeeececfccccceccececeeeeeeeeeeeeeeeeeeeeeeeeebeeb44fffcccffffebbffffbbbbbbecfefffffcfbbbbbeebeeeebebeeeeeeceecceeee
ffffffffffffffffffffffcfffffffffffcffffeeeeeebeeeececeecfebfcceefeeeeeefeeeecbeeeeeeeeeeeee44effffcfcffffc4bffffffebbbfffffffffffbbbbbebeeeeeeeeeeceeeeeffceeee
fffcffffffffffffffffcffffeffffffcfcfffeeeeccecccecceeebbbeebefebefeeeeceeefe4efeeeccfeeebeeeecffffffffffffffffffffbebbfffffffffffebbebbbbbbecbebbeeeeeeeebeeece
ffffffcfffffffffffffffffcfffefcffffffffeefeeeeceeeeeeeeeceecefeeeeccebfcfecceeeeeee4eeeeeeeeeefffcffffffffffffffffefeeffffffffffffbbbebbeebbebeeeebeeeeeeefeeee
fffffffffffffffffffffcfffefffccffffefffeefeececccecfeeeeeefebeefffffeffefffceeeecceeeb44eebeebeffcffffffffffffffffefffffffffffffffbbbbbbbeeebbbbeeeeebeeeeeeeec
ffffffffffffffffffffffffffffccfffcfcfccefffffceffceccfeeecfffefffffffffffffcfffefefeeffeeeeeeeefffcfffffffffffffffefffffffffffffffebbbeeebebeeeeeeeeeeeeeeeeeec
ffffffffffffffffffffffffffffcffcffcffffffeffffffffccffefcfffffffffffffffffffffcfffffeeefeeceeeffffcfffffffeeffffffeeeecffffffffffbbbbbeeeeceeeeebeeeeeeeeceecec
ffffffffffffffffffffffffffceffffffffffffcfffcfffffffffffffffffffcfffefffffffffffcfffffffffcefffecffffffffcceffffffeefefffffffffffbbbbebeeeeeeceecbceececeeeccce
ffffffffffffffffffffffffffffffeffffffffffffcfceefffffffffffffcfffffecfffffffffcccfcffffffcfffffffffffffffcffffffffeefffffffffffffeeeeceeeeeeeeeeeeeeeeeeeeeeeec
fffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffcfffffcfceffcfffccffffccfcfcffffffffffeefffffffeecffffffffffffeeeeeeeeceeececeeeeeeeceececcc
fffffffffffffffffffffffffcfffffffffffffffffffffcfffcffffcffffffffffffffffcfffffffffffffffffffffffffffffffcefffffffeffffffffffffffeceececeeefffefcbceeeecefcefcf
ffffffffffffffffffffffffffffffffffffffcffffffffffffcffffffffffffffffffffffcfffffffcfffffffffffffffffffffffffffffffeffffffffffcfffceeeeeeeceeeeeeeceeceeeccccece
fffffffffffffffffffffffffffffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcceeeeeecccfffcfcecccccccccefc
fffffffffffffffffffffffffffffffffcfffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeccceeecceeefcccccccfcccfeccec
fffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffcccccccccecccccceeccfffcccfcfce
ffffffffffffffffffffffffffffffffffffffccfffcfffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfecfeffeffcceccccffffeffef
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffcfffcffceccccfefceeeecfcccfcfccc
`;
            case "h-v*[Q3kfO+/J6[hpfT$":
            case "nøgle":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "zombie":return img`
.......................................
.............db7777b...................
...........be7777777b..................
..........cc777777777d.................
.........df7777777777b.................
.........df7777777e7bed................
.........bf7777ee777dbd................
.........dfc77bdde77ebb................
.........bffeeddbb77e7b................
.........bcfe7bbbbe7feb................
.........dbce7eeeeeeeeb................
...........ee77777777ec................
..........dbeee777ebccc................
..........b.db777eeb7eed...............
...............de7ee7e7b...............
...............d7e77777d........dbd....
...............bd7e77bdddddddbb77eee...
..............bdbeefeebdddbddb7e7b7fd..
.............bddddecbdbbbbbdbbbeecdd...
.............beeddecddb................
.............decddbebdb................
.............b7dbddecdb................
.............7bdbddefbb................
............d7d1eddeeeb................
............d77dbddeeeb................
.............db7eeeeeeed...............
...............d777eefcc...............
...............d777eccccb..............
...............bbeeecccccb.............
................dcfccdccccb............
................bcccd.dcccc............
................cccc....fccd...........
...............deecd....cccd...........
...............bccb.....bcccd..........
...............ccc......bcccb..........
..............dcfc......dffffeb........
..............dfff......dcfcfffd.......
..............dccb.......dd.ddd........
.......................................
.......................................
`;
            case "image7":
            case "zombie2":return img`
. . . . . . 7 7 f 2 . . . . . 
. . . b 7 7 7 7 f 2 2 d . . . 
. . b 7 7 7 7 7 f 2 d 2 d . . 
. b 7 7 7 7 7 7 7 f 2 d 2 d . 
. b 7 7 7 7 7 7 7 7 f 2 d 2 . 
. b 7 7 7 7 7 7 7 7 7 f 2 2 . 
. b 7 7 7 7 7 7 7 7 7 7 f f . 
. 7 7 7 7 b f 7 7 f b 7 7 7 7 
. 7 7 7 7 1 f 7 7 f 1 7 7 7 7 
. . 7 7 7 7 7 7 7 7 7 7 7 7 . 
. . c 7 7 7 7 7 7 7 7 7 7 . . 
. . 7 7 f 2 2 2 2 2 2 f 7 7 . 
. c 7 7 f 2 2 2 2 2 2 f 7 7 . 
. . 7 7 f 4 4 5 5 4 4 f 7 7 . 
. . . . . f f f f f f . . . . 
. . . . . f f . . f f . . . . 
`;
            case "image8":
            case "vampyr":return img`
. . f f f . . . . . . . . . . . 
f f f c c . . . . . . . . f f f 
f f c c c . c c . . . f c b b c 
f f c 3 c c 3 c c f f b b b c . 
f f c 3 b c 3 b c f b b c c c . 
f c b b b b b b c f b c b c c . 
c c 1 b b b 1 b c b b c b b c . 
c b b b b b b b b b c c c b c . 
c b 1 f f 1 c b b c c c c c . . 
c f 1 f f 1 f b b b b f c . . . 
f f f f f f f b b b b f c . . . 
f f 2 2 2 2 f b b b b f c c . . 
. f 2 2 2 2 2 b b b c f . . . . 
. . f 2 2 2 b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "up":
            case "anim1":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f f 2 f e f . . 
. . f f f 2 f e e 2 2 f f f . . 
. . f e 2 f f e e 2 f e e f . . 
. f f e f f e e e f e e e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . . e f f f f f f f f 4 e . . 
. . . 4 f 2 2 2 2 2 e d d 4 . . 
. . . e f f f f f f e e 4 . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f 2 2 f f f f . . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e f 2 f f f 2 f 2 e f . . 
. . f f f 2 2 e e f 2 f f f . . 
. . f e e f 2 e e f f 2 e f . . 
. f f e e e f e e e f f e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f e . . . 
. . 4 d d e 2 2 2 2 2 f 4 . . . 
. . . 4 e e f f f f f f e . . . 
. . . . . . . . . f f f . . . . 
`];
            case "left":
            case "anim2":return [img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f 2 2 e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f 2 2 2 e d d 4 . . . . . 
. . . f 2 2 2 e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f 2 f e e e e f f . . . . 
. . f 2 2 2 f e e e e f f . . . 
. . f e e e e f f e e e f . . . 
. f e 2 2 2 2 e e f f f f . . . 
. f 2 e f f f f 2 2 2 e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f 2 2 2 2 e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
            case "right":
            case "anim3":return [img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e e e d d d f . . . 
. . . . . f 4 d d e 4 e f . . . 
. . . . . f e d d e 2 2 f . . . 
. . . . f f f e e f 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`, img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . 4 d d e 4 4 4 e f . . . 
. . . . e d d e 2 2 2 2 f . . . 
. . . . f e e f 4 4 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`];
            case "down":
            case "anim4":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . . f e 4 d d d d 4 e f e . . 
. . f e f 2 2 2 2 e d d 4 e . . 
. . e 4 f 2 2 2 2 e d d e . . . 
. . . . f 4 4 5 5 f e e . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f e e 2 2 2 2 2 2 e f f . . 
. f f e 2 f f f f f f 2 e f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . e f e 4 d d d d 4 e f . . . 
. . e 4 d d e 2 2 2 2 f e f . . 
. . . e d d e 2 2 2 2 f 4 e . . 
. . . . e e f 5 5 4 4 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . f f f . . . . 
`];
            case "nøgleanimation":
            case "anim5":return [img`
. . . . . . . . . . . . . . . . 
. . . 5 5 5 5 5 5 . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 5 . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. 5 5 5 5 . . . . . . . . . . . 
5 5 4 4 5 5 . . . . . . . . . . 
5 5 4 . 5 5 . . . . . . . . . . 
5 5 5 5 5 4 . . . . . . . . . . 
. 5 5 5 4 . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . 5 5 5 5 5 5 . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 5 5 5 5 . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. . . 5 . . . . . . . . . . . . 
. 5 5 5 5 . . . . . . . . . . . 
5 5 4 4 5 5 . . . . . . . . . . 
5 5 4 . 5 5 . . . . . . . . . . 
5 5 5 5 5 4 . . . . . . . . . . 
. 5 5 5 4 . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "kisteanimation":
            case "anim6":return [img`
. . b b b b b b b b b b b b . . 
. b e 4 4 4 4 4 4 4 4 4 4 e b . 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
. b b . . . . . . . . . . b b . 
`, img`
. b b b b b b b b b b b b b b . 
b e 4 4 4 4 4 4 4 4 4 4 4 4 4 b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b b b b b b b d d b b b b b b b 
. b b b b b b c c b b b b b b . 
b c c c c c b c c b c c c c c b 
b c c c c c c b b c c c c c c b 
b c c c c c c c c c c c c c c b 
b c c c c c c c c c c c c c c b 
b b b b b b b b b b b b b b b b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
. b b . . . . . . . . . . b b . 
`];
            case "myAnim":
            case "anim7":return [img`
. . . b 7 7 7 7 . . . . . . . . 
. . d 7 7 7 7 7 b . . . . . . . 
. . b 7 7 e 7 7 b . . . . . . . 
. . b f e d b 7 7 . . . . . . . 
. . d c 7 e e e e . . . . . . . 
. . . b e 7 7 b c . . . . . . . 
. . . . . d 7 e e b . . . . . . 
. . . . . b 7 7 b d d d b 7 e e 
. . . . b d d c d b b d b e c d 
. . . . b d d e d . . . . . . . 
. . . . 7 1 d e e . . . . . . . 
. . . . d 7 e e e d . . . . . . 
. . . . . d 7 e c c . . . . . . 
. . . . . . c c d c c . . . . . 
. . . . . . c c . . c d . . . . 
. . . . . b c . . . c c . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
